### ISSUE TITLE
Add loadProgram()

### ISSUE THREAD

**Issue by smj-edison** [CS-Underground/backend#19]
A lot of times, with big programs on khanacademy, the code gets really cluttered because of how big it is. It would be really useful if you could run something like: `var foo = loadProgram("0000000235");`, and use `model.exports` like how node.js does it. I have a half working prototype [here](https://csunderground.org/program/0000000233), but I can't get processing functions to work.

**Comment by codeHusky** [comment]
This is more of an issue for the https://github.com/CSUnderground/live-editor fork rather than the backend. Please request this over there <3
